### ISSUE TITLE
Crashes when loading Hazy Maze Cave in fullscreen.

### ISSUE THREAD

**Issue by gunvalk** [sm64pc/sm64pc#57] opened 2020-05-10 22:36 UTC
After the star select screen the game will crash when loading the level, but only in fullscreen. Can be reproduced.

**Comment by Zero-Shift** [comment] 2020-05-11 03:08
Able to reproduce the issue. To add on, entering Hazy Maze Cave windowed **then** going full screen works fine.

**Comment by urherenow** [comment] 2020-05-11 06:13
Where does BETTERCAMERA=1 go? I tried adding it to the .ini and nothing happens, and it always gets deleted (from the master branch) and it's the same thing when launching the .exe with BETTERCAMERA=1.

**Comment by Hyenadae** [comment] 2020-05-13 13:58
We're fixing another issue related to graphics pool size, but I'm going to check into this myself.

**Comment by vrmiguel** [comment] 2020-05-13 14:27
@gunvalk @Zero-Shift 
Please try to reproduce this issue using master's latest commit.

**Comment by Zero-Shift** [comment] 2020-05-13 18:20
@vrmiguel Issue seems to be fixed now, thanks!

**Comment by gunvalk** [comment] 2020-05-13 20:30
@vrmiguel yep its fixed! you guys are the best.

**Closed** 2020-05-13 20:30 UTC
Labels: bug

**Comment by Benchamoneh** [comment] 2020-05-15 12:47
More information just for awareness, I was able to reproduce this bug both windowed and fullscreen, seems the issue was not in the application being fullscreen but rather the aspect ratio. Resizing the window to a non 4:3 ratio (stretching it out wide) caused the game to crash for me even windowed.
