### ISSUE TITLE
Jolly Roger Bay coin/star crash

### ISSUE THREAD

**Issue by Filipianosol** [sm64pc/sm64pc#90] opened 2020-05-13 22:59 UTC
During the course Jolly Roger Bay the port sometimes crashes when collecting a coin or a star. Happens both in fullscreen and windowed mode.

**To Reproduce**
1. Enter Jolly Roger Bay
2. Select the mission Plunder in the Sunken Ship (coins) or the mission Can the Eel Come Out to Play? (star). Perhaps other missions also crash but for now that remains unconfirmed
3. Try to catch a coin. One of the coins in the coin circle before the tunnel is confirmed to crash in my clip. The mission I selected in the clip is Plunder in the Sunken Ship. The coins from the box near the spawn point also crashed the game but the coin ring is the most tested by me. Catching some stars also works. User cockgoblin confirmed that the star in Can the Eel Come Out to Play? also causes a crash.

![Jolly Roger Bay coin circle crash](https://user-images.githubusercontent.com/12639838/81874216-b8acbb80-957d-11ea-9fa9-38cd9cfd4254.gif)

OS: Windows 10 64-bit
Build contains commit [Fix some overflow issues](https://github.com/sm64pc/sm64pc/commit/d5d151f322ada2d9152a573aec00770d5720a4e6). 

EDIT:
Compiled with flags BETTERCAMERA=1 and nodrawingdistance=1.
[Save download](https://mega.nz/file/ARs3UKxA#eC1K8j5F1QeUpAS6kL3qTrwgvjAgVX9b7hLM6-76yVE)

**Comment by uncletrunks** [comment] 2020-05-13 23:30
Does not appear to be the case in my build. Arch Linux x86_64, latest commit as of writing, built with `make BETTERCAMERA=1`.

**Comment by Zero-Shift** [comment] 2020-05-14 00:39
I was not able to replicate this issue on the latest master, both on Analog and normal

**Comment by Patjwmiller** [comment] 2020-05-14 01:31
I also can not reproduce this crash, even with the overflow fix.

**Comment by InsanityOnABun** [comment] 2020-05-14 02:11
Able to recreate with coins around the spike involved in Blast to the Stone Pillar.

**Comment by InsanityOnABun** [comment] 2020-05-14 02:38
Able to consistently recreate now with the coins around the spike. Select star 3, Treasure of the Ocean Cave, when entering the level.

**Comment by Filipianosol** [comment] 2020-05-14 13:33
> Does not appear to be the case in my build. Arch Linux x86_64, latest commit as of writing, built with `make BETTERCAMERA=1`. If we could get the build flags you used as well as possibly your save file that'd help.

The flags are BETTERCAMERA=1 and nodrawingdistance=1. [Save](https://mega.nz/file/ARs3UKxA#eC1K8j5F1QeUpAS6kL3qTrwgvjAgVX9b7hLM6-76yVE)

**Comment by Patjwmiller** [comment] 2020-05-14 15:40
So I made an attempt at a longer play of this area. I can not reproduce this crash with given information. Flags set to the appropriate and still nothing.

**Comment by gunvalk** [comment] 2020-05-14 15:42
I've not been able to make it crash either, but I have seen several people who are having this issue.

**Comment by InsanityOnABun** [comment] 2020-05-15 21:56
Crashing occurs with the draw distance patch, and does not without.

**Comment by Filipianosol** [comment] 2020-05-15 22:14
Same behavior for me

**Comment by Torbulous** [comment] 2020-05-16 13:12
Tried it. Can confirm that I'm having the same issue. It didn't happen with my own save though. Also I collected a different coin and had the game crash on me. Not sure how important that is.

**Comment by Filipianosol** [comment] 2020-05-16 13:54
@Torbulous I tried with your save. 3 tries and no crash. I also tried it with a clean save without NODRAWINGDISTANCE in the Makefile and it crashed when I used it on a NODRAWINGDISTANCE build. So there is a conflict between clean saves without NODRAWINGDISTANCE and saves with NODRAWINGDISTANCE it seems. Also, you don't have to go all the way to te coin ring, I think any coin causes a crash. Tried one of those that surround the spike and also crashed.

I think the problem might be how NODRAWINGDISTANCE saves register coins vs how w/o NODRAWINGDISTANCE saves register them. For now we have to use separate clean NDD saves and w/o NDD clean saves to avoid coin/star crashes.

**Comment by fgsfdsfgs** [comment] 2020-05-16 14:03
If possible, run the game under gdb while trying to catch the crash. Once it crashes, enter `bt` in the gdb prompt and copypaste the output to this thread. That'll make it easier to pinpoint.

**Comment by natepley** [comment] 2020-05-16 14:34
I'm using 8.6 and I got the crash.  I've tried it 3 times.  Twice, I hit the block behind the starting point and crashed when I picked up one of the coins that came out.  Once, I crashed when I picked up an underwater coin in the ring.  After that, I just stopped going to that level.

**Comment by gunvalk** [comment] 2020-05-16 15:38
I was finally able to make mine crash. It looks like if you use a save file that was created before the nodrawingdistance mod was added then it does not result in a crash when collecting the coin. When using a fresh save file started while using nodrawingdistance mod then jrb will crash when collecting the coin.

**Comment by fgsfdsfgs** [comment] 2020-05-16 20:50
That ain't right. Did you run it from `cmd` or something?

**Comment by gunvalk** [comment] 2020-05-16 21:30
> That ain't right. Did you run it from `cmd` or something?

I haven't used gdb before so i wasn't sure what i was supposed to be looking for. I ran it with msys2. when the crash happened i put bt but that didn't seem to do anything, and that's what populated after I force closed the window.

**Comment by fgsfdsfgs** [comment] 2020-05-16 22:19
Oh. You gotta type `bt` then press Enter.

**Comment by gunvalk** [comment] 2020-05-16 22:23
lol yeah I pressed enter.

**Comment by Leon422** [comment] 2020-05-17 11:42
> 
> 
> I was finally able to make mine crash. It looks like if you use a save file that was created before the nodrawingdistance mod was added then it does not result in a crash when collecting the coin. When using a fresh save file started while using nodrawingdistance mod then jrb will crash when collecting the coin.
> 
> Edit: @fgsfdsfgs I ran it with gdb and this is what I got on crash
> `bt [Thread 1652.0x265c exited with code 1] [Thread 1652.0x204c exited with code 1] [Thread 1652.0x950 exited with code 1] [Thread 1652.0x33dc exited with code 1] [Thread 1652.0x2fa8 exited with code 1] [Thread 1652.0x28fc exited with code 1] [Thread 1652.0x2ae0 exited with code 1] [Thread 1652.0x9b4 exited with code 1] [Thread 1652.0x814 exited with code 1] [Inferior 1 (process 1652) exited with code 01] `
> 
> >

Nope. My saved game was created before the NODRAWINGDISTANCE mod existed, and my game has crashed a few times picking up coins in JBB. Windows 64 bit, NODRAWINGDISTANCE and BETTERCAMERA both enabled.

**Comment by coltongit** [comment] 2020-05-17 12:03
I wonder if the GFX_POOL_SIZE increase that was pushed in recent commits had something to do with this. In which case, try to reproduce this again with the latest master (which should have the GFX_POOL_SIZE increase already) and see if any of you can get this to happen still

**Comment by hunterzero99** [comment] 2020-05-17 12:59
Crash is still happening to me, I've tried with a 64bit Windows build and 32bit built from the latest master.  I haven't been able to figure out gdb yet, i'll try to post a log of it later today if that will help.

**Comment by gunvalk** [comment] 2020-05-17 17:50
Can also confirm the crash is still happening with latest master.

**Comment by Filipianosol** [comment] 2020-05-18 17:45
The crash is still here with the latest master and nightly. Indeed doesn't seem to be related to saves at all as I tried various saves.

**Comment by pouar** [comment] 2020-05-19 21:23
Here's a more useful backtrace in case it's helpful to anyone.
![image](https://user-images.githubusercontent.com/1709744/82379395-7572a280-99ec-11ea-9fbe-c556bb8f3471.png)
![image](https://user-images.githubusercontent.com/1709744/82379407-7acfed00-99ec-11ea-8fa8-bb34b84fe78b.png)

**Comment by IvanDSM** [comment] 2020-05-21 01:43
Pushed a potential fix for this on the nightly branch. Could you please test it out @Filipianosol?

**Comment by Plynthus** [comment] 2020-05-21 02:18
I just tested. No crashes at all. Not here or Rainbow Ride (issue #113).
For me the Rainbow Ride one has been crashing 100% of the time with nodrawingdistance=1. And Jolly Roger Bay about 95% of the time.

I tried both only 3 times, because I have to go to work. But with earlier builds there would have been 5-6 crashes by now.

**Comment by Patjwmiller** [comment] 2020-05-21 17:13
indeed was OBJECT_POOL_CAPACITY IvanDSM

**Comment by Filipianosol** [comment] 2020-05-21 18:18
Seems to be fixed. Before I close this issue however, I'd like to ask a question that's related to my assumption about the save system. Is it possible that using an old save that was started on an earlier version on a newer one might cause instabilities like more crashes?

**Closed** 2020-05-24 15:21 UTC
Labels: bug
