### ISSUE TITLE
Rainbow Ride freeze/crash

### ISSUE THREAD

**Issue by Mastergatto** [sm64pc/sm64pc#113] opened 2020-05-15 19:07 UTC
**Describe the bug**
The game freezes in a particular point of the stage "Rainbow Ride".

**To Reproduce**
1. Go to 'Rainbow Ride', course 15, select the "Swingin' in the breeze" level.
2. Take the path for the star for this level, where there's a fly guy, some swinging platform and such. Try to land in a falling platform.
4. Freeze.

**Screenshots**
![freeze](https://user-images.githubusercontent.com/1028191/82087112-c1250380-96ef-11ea-9049-234f68165394.png)

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Version: eb08446 compiled with BETTERCAMERA=1 NODRAWINGDISTANCE=1
- Save file: [sm64_save_file.zip](https://github.com/sm64pc/sm64pc/files/4636802/sm64_save_file.zip)

**Additional context**
Bug similar to #90. It seems to run fine without issues without NODRAWINGDISTANCE compiling flag.

**Comment by coltongit** [comment] 2020-05-17 12:03
I wonder if the GFX_POOL_SIZE increase that was pushed in recent commits had something to do with this. In which case, try to reproduce this again with the latest master (which should have the GFX_POOL_SIZE increase already) and see if any of you can get this to happen still

**Comment by Mastergatto** [comment] 2020-05-17 12:25
It still freezes...

**Comment by derailius** [comment] 2020-05-20 00:06
> 
> 
> It still freezes...It could be that those falling platforms are still subject to drawing distance? When I was far enough, I couldn't see them.

yes, vanilla won't crash, but with drawing distance it crashes.

**Comment by coltongit** [comment] 2020-05-21 02:22
A fix for this has just went out to nightly. Please test again and see if your issue persists.

**Comment by derailius** [comment] 2020-05-21 03:36
> 
> 
> A fix for this has just went out to nightly. Please test again and see if your issue persists.

in jolly roger bay as soon as try to grab the star after knocking it off of the eel the game freezes. tried it twice now, with brand new nightly.

**Comment by IvanDSM** [comment] 2020-05-21 04:07
> > A fix for this has just went out to nightly. Please test again and see if your issue persists.
> 
> in jolly roger bay as soon as try to grab the star after knocking it off of the eel the game freezes. tried it twice now, with brand new nightly.

I couldn't reproduce the freezing. Could you please send me your save file?

**Comment by derailius** [comment] 2020-05-21 05:31
steps to reproduce, load first save slot go to straight to jolly roger bay, select mission "can the eel come out and play"  jump in the water, don't collect any coins, go straight to the eel, knock the star off of his tail, and when you go to collect it, the game freezes.
[sm64_save_file.zip](https://github.com/sm64pc/sm64pc/files/4660724/sm64_save_file.zip)

**Comment by IvanDSM** [comment] 2020-05-21 15:11
> steps to reproduce, load first save slot go to straight to jolly roger bay, select mission "can the eel come out and play" jump in the water, don't collect any coins, go straight to the eel, knock the star off of his tail, and when you go to collect it, the game freezes.
> [sm64_save_file.zip](https://github.com/sm64pc/sm64pc/files/4660724/sm64_save_file.zip)

I can reproduce the issue with the provided savefile on the master branch, but I'm unable to reproduce it in the nightly branch.

**Comment by derailius** [comment] 2020-05-21 15:13
> 
> 
> > steps to reproduce, load first save slot go to straight to jolly roger bay, select mission "can the eel come out and play" jump in the water, don't collect any coins, go straight to the eel, knock the star off of his tail, and when you go to collect it, the game freezes.
> > [sm64_save_file.zip](https://github.com/sm64pc/sm64pc/files/4660724/sm64_save_file.zip)
> 
> I can reproduce the issue with the provided savefile on the master branch, but I'm unable to reproduce it in the nightly branch.

with NODRAWINGDISTANCE=1 ?

**Comment by Plynthus** [comment] 2020-05-21 15:25
The can the eel come out and play star crash didn't happen for me either in nightly. After multiple attempts in different ways with NODRAWINGDISTANCE=1

**Comment by IvanDSM** [comment] 2020-05-21 15:28
> > > steps to reproduce, load first save slot go to straight to jolly roger bay, select mission "can the eel come out and play" jump in the water, don't collect any coins, go straight to the eel, knock the star off of his tail, and when you go to collect it, the game freezes.
> > > [sm64_save_file.zip](https://github.com/sm64pc/sm64pc/files/4660724/sm64_save_file.zip)
> > 
> > 
> > I can reproduce the issue with the provided savefile on the master branch, but I'm unable to reproduce it in the nightly branch.
> 
> with NODRAWINGDISTANCE=1 ?

Yes, using `BETTERCAMERA=1 NODRAWINGDISTANCE=1`

**Comment by derailius** [comment] 2020-05-21 15:38
> 
> 
> > > > steps to reproduce, load first save slot go to straight to jolly roger bay, select mission "can the eel come out and play" jump in the water, don't collect any coins, go straight to the eel, knock the star off of his tail, and when you go to collect it, the game freezes.
> > > > [sm64_save_file.zip](https://github.com/sm64pc/sm64pc/files/4660724/sm64_save_file.zip)
> > > 
> > > 
> > > I can reproduce the issue with the provided savefile on the master branch, but I'm unable to reproduce it in the nightly branch.
> > 
> > 
> > with NODRAWINGDISTANCE=1 ?
> 
> Yes, using `BETTERCAMERA=1 NODRAWINGDISTANCE=1`
> 
> Could you please try running make clean before rebuilding? Make sure to backup your save file first.

well, i don't know what happened, but it's working now. maybe i just didn't have the latest nightly, i'm so very sorry to have wasted your time like this.

**Comment by coltongit** [comment] 2020-05-21 16:09
It's OK. Happy to help with your issue

**Comment by Mastergatto** [comment] 2020-05-21 17:27
I can't reproduce the issue with nightly build, it seems. So can we consider it being fixed?

**Comment by derailius** [comment] 2020-05-21 17:28
> 
> 
> I can't reproduce the issue with nightly build, it seems. So can we consider it being fixed?

seems to be working fine for me. thanks again.

**Comment by IvanDSM** [comment] 2020-05-21 17:29
Since nobody (including the original reporter) can reproduce the issue we'll consider this closed. If anyone runs into this same issue again on latest nightly we can reopen it.

**Closed by IvanDSM** 2020-05-21 17:29 UTC
Labels: bug

**Comment by Plynthus** [comment] 2020-05-21 18:29
I know this is closed but if it’s ok to ask here. Is it necessary for the functionality of those falling platforms to still have limited drawing distance when nodrawdistance=1? Or is it possible to have those with no draw distance in the future as well?
